### ISSUE TITLE
QR Code Inside Console

### ISSUE THREAD

**Issue by MysteryBlokHed** [Aayush9029/Rifi#10]
By the looks of it, the QR Code opens in the default image viewer for whatever OS is running the Python app. If the QR code was displayed in the console, it could be a bit better to have it all in one window.

I quickly set up [a library that does this](https://github.com/MysteryBlokHed/QRConsole) which should work pretty well for it. It just needs a path to a file containing the QR code, so the QR code would need to be saved to a temporary file of some sort.

**Comment by kvosbur** [comment]
That would be a lot better. Never actually thought of doing that. While the qr isn't quite as necessary now that we are using static ports, it would still be a nice addition

**Comment by Aayush9029** [comment]
I love the idea, saw your comment on reddit. 

Does it work on windows computer (command prompt) and is it the quality good enough for a phone to scan ?

Great work on the library.

  If you want I’ll import your library and use that instead of pillow.

**Comment by Aayush9029** [comment]
Do you think you’ll be able to make a pip package? @MysteryBlokHed

**Comment by MysteryBlokHed** [comment]
The package is currently on PyPI ([qrconsole](https://pypi.org/project/qrconsole/)), and I've tested it on Windows. The QR code is scannable, but it currently might be too large to display, since the library maps each pixel to a character. If you use the QRCode class (from the `qrcode` library already in use), you'll be able to turn the code into a Pillow image class, then resize it using `.resize`.

**Comment by Aayush9029** [comment]
I'll implement this feature or a similar feature on this weekend. Thanks a lot @MysteryBlokHed.

**Comment by MysteryBlokHed** [comment]
I just made a quick update to the module that I figured I should mention. You can now just pass the Pillow `Image` object as an argument instead of a path to the image on disk. You can also resize the image through the main function.
Hopefully this will make it a lot easier to implement, since there's no longer a need to save the image to disk first.

**Comment by Aayush9029** [comment]
@MysteryBlokHed, Thanks for your suggestion like you said I changed main.py so that now QR code is displayed inside the terminal rather than being opened by Pillow "image". I tried using your library and it didn't seem to work on macOS Catalina so I used another similar one which works. Thanks a lot for the suggestions feel free to fork the repo if you want to change the QR module.

#10 has been closed for now thanks again.
